### ISSUE TITLE
Errors Compiling with MySensors 2.2

### ISSUE THREAD

**Issue by bnorth12** [EasySensors/ButtonSizeNode2#1]
The updates to MySensors that now include a MyConfig.h header change the locations for definitions. The radio selction should still be included in the ButtonSizeNode.ino file however the frequencies for the Radio shpuld be set in the MyConfig.h.

// Enable and select radio type attached
#define MY_RADIO_RFM69
//#define MY_RFM69_FREQUENCY   RF69_433MHZ
//#define MY_RFM69_FREQUENCY   RF69_868MHZ

**Comment by yurysvirida** [comment]
did you define `#define MY_RFM69_FREQUENCY RFM69_XXXMHZ `  before `#include <MySensors.h>` ?

**Comment by bnorth12** [comment]
Could not duplicate error.
